//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alergomurcia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reunione
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string titulo { get; set; }
        public string lugar { get; set; }
        public string resumen { get; set; }
        public string detalle { get; set; }
        public string enlaces { get; set; }
        public byte[] documento { get; set; }
    }
}
