//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alergomurcia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> login { get; set; }
        public Nullable<bool> articulos_insertar { get; set; }
        public Nullable<bool> articulos_editar { get; set; }
        public Nullable<bool> articulos_eliminar { get; set; }
        public Nullable<bool> reuniones_insertar { get; set; }
        public Nullable<bool> reuniones_editar { get; set; }
        public Nullable<bool> reuniones_eliminar { get; set; }
        public Nullable<bool> noticias_insertar { get; set; }
        public Nullable<bool> noticias_editar { get; set; }
        public Nullable<bool> noticias_eliminar { get; set; }
        public Nullable<bool> usuarios_activar { get; set; }
        public Nullable<bool> usuarios_permisos { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> subir_ficheros { get; set; }
        public string apellidos { get; set; }
        public string dni { get; set; }
        public string fecha_nacimiento { get; set; }
        public string direccion_particular { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string codigo_postal { get; set; }
        public string email { get; set; }
        public string telefono_movil { get; set; }
        public string telefono_fijo { get; set; }
        public string puesto_trabajo { get; set; }
        public string centro_trabajo { get; set; }
        public string direccion_trabajo { get; set; }
        public string localidad_trabajo { get; set; }
        public string provincia_trabajo { get; set; }
        public string codigo_postal_trabajo { get; set; }
        public string telefono_trabajo { get; set; }
        public string nombre1_aval { get; set; }
        public string email1_aval { get; set; }
        public string nombre2_aval { get; set; }
        public string email2_aval { get; set; }
        public string banco { get; set; }
        public string direccion_banco { get; set; }
        public string localidad_banco { get; set; }
        public string titular { get; set; }
        public string codigo_entidad { get; set; }
        public string codigo_sucursal { get; set; }
        public string codigo_control { get; set; }
        public string codigo_cuenta { get; set; }
        public Nullable<System.DateTime> alta { get; set; }
    }
}
